### ISSUE TITLE
Displaying &pound; not £ and returning 0

### ISSUE THREAD

**Issue by Caroline-Elisa** [CodersPress/jQuery-Currency#2]
Hi gilbitron,

I am trying to use your neat plugin on a Wordpress site, but am only getting &pound;0.00 as a result. I don't mind turning of the prefix if the parsing is an issue, but I would like to figure out how to get the converter working!

Here is the page: http://indigobrazilianportuguese.com/test-3/?val=200

And the code (identical for each input, the difference between each input being how the values are originally set to 200:

```
$('#input_6_2').currency({ region: 'GBP', convertFrom: 'USD', convertLocation: 'http://indigobrazilianportuguese.com/2012/wp-content/themes/indigo/js/currency/convert.php' });
$('#input_6_4').currency({ region: 'GBP', convertFrom: 'USD', convertLocation: 'http://indigobrazilianportuguese.com/2012/wp-content/themes/indigo/js/currency/convert.php'});
$('#input_6_5').currency({ region: 'GBP', convertFrom: 'USD', convertLocation: 'http://indigobrazilianportuguese.com/2012/wp-content/themes/indigo/js/currency/convert.php'});
```

Hoping you can help!

Thanks,
Caroline

**Comment by gilbitron** [comment]
Hi Caroline

It looks like the inputs have no value when the page loads, so when you are making the call it is returning £0.00. The reason you are seeing `&pound;` is because the value is being returned in an input box, and not in HTML.

Gilbert
