### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known 

### ISSUE THREAD

**Issue by rajeshkw** [CodersPress/jQuery-Currency#8]
Warning (2): file_get_contents() [function.file-get-contents]: php_network_getaddresses: getaddrinfo failed: Name or service not known [APP/Controller/convert.php]
My Php version is 5.2.16.

I probably made no mistake..what could be the issue?

**Comment by edbrownlie** [comment]
check open url is on in php.ini
