### ISSUE TITLE
crashed after server move

### ISSUE THREAD

**Issue by edbrownlie** [CodersPress/jQuery-Currency#9]
# displaying error Parse error: syntax error, unexpected '<' in /home2/conc#####/public_html/convert.php(40) : eval()'d code on line 1

was  fine before move but i can not see the error

**Comment by CodersPress** [comment]
This file has been updated to Googles new system and URLS

You should bare in mind its just a sample file that grabs the Amount, Currency From and Currency TO

Side note: eval()'d code ? would not have been part of this original file
